# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import atari_pb2 as proto_dot_atari__pb2


class AtariStub(object):
  """Atari service allows for reinforcement agents to play atari over the network.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Start = channel.unary_unary(
        '/atari.Atari/Start',
        request_serializer=proto_dot_atari__pb2.Environment.SerializeToString,
        response_deserializer=proto_dot_atari__pb2.Observation.FromString,
        )
    self.Step = channel.unary_unary(
        '/atari.Atari/Step',
        request_serializer=proto_dot_atari__pb2.Action.SerializeToString,
        response_deserializer=proto_dot_atari__pb2.State.FromString,
        )


class AtariServicer(object):
  """Atari service allows for reinforcement agents to play atari over the network.
  """

  def Start(self, request, context):
    """Start initialises and resets the environment.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Step(self, request, context):
    """Step applies the action to the active environment and returns the state.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AtariServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Start': grpc.unary_unary_rpc_method_handler(
          servicer.Start,
          request_deserializer=proto_dot_atari__pb2.Environment.FromString,
          response_serializer=proto_dot_atari__pb2.Observation.SerializeToString,
      ),
      'Step': grpc.unary_unary_rpc_method_handler(
          servicer.Step,
          request_deserializer=proto_dot_atari__pb2.Action.FromString,
          response_serializer=proto_dot_atari__pb2.State.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'atari.Atari', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
